// DO NOT EDIT THIS FILE!!! IT WILL BE AUTOMATICALLY GENERATED FROM src/i18n
/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "on save adapter restarts with new config immediately": {"en": "on save adapter restarts with new config immediately", "de": "Beim Speichern von Einstellungen der Adapter wird sofort neu gestartet.", "ru": "При сохранении настроек адаптера он сразу же перезапускается", "pt": "no adaptador de salvar reinicia com nova configuração imediatamente", "nl": "on save-adapter wordt onmiddellijk opnieuw opgestart met nieuwe config", "fr": "sur l'adaptateur de sauvegarde redémarre avec la nouvelle config immédiatement", "it": "su save adapter si riavvia immediatamente con la nuova configurazione", "es": "en el adaptador de guardar se reinicia con nueva configuración de inmediato"},
    "template adapter settings": {                   "en": "template adapter settings",                       "de": "Beispiel",                                        "ru": "Пример",                                          "pt": "configurações do adaptador de modelo",            "nl": "sjabloon-adapterinstellingen",                    "fr": "paramètres de l'adaptateur de modèle",            "it": "impostazioni dell'adattatore del modello",        "es": "configuración del adaptador de plantilla"},
    "arping_time": {                                       "en": "Presence scan",                                          "de": "Test 1",                                          "ru": "Тест 1",                                          "pt": "Teste 1",                                         "nl": "Test 1",                                          "fr": "Test 1",                                          "it": "Test 1",                                          "es": "Prueba 1"},
    "arpscan_time": {                                       "en": "Test 2",                                          "de": "Test 2",                                          "ru": "Тест 2",                                          "pt": "Teste 2",                                         "nl": "Test 2",                                          "fr": "Test 2",                                          "it": "Test 2",                                          "es": "Prueba 2"}
    "Scan for new devices every x minutes": {
       "nl": "Scan for new devices every x minutes",
       "en": "Scan for new devices every x minutes",
       "de": "Scanne alle x Minuten nach neuen Geräten",
       "fr": "Scan for new devices every x minutes",
       "ru": "Scan for new devices every x minutes",
       "it": "Scan for new devices every x minutes",
       "es": "Scan for new devices every x minutes",
       "pt": "Scan for new devices every x minutes"
    },
    "Presence scan every x seconds": {
       "nl": "Presence scan every x seconds",
       "en": "Presence scan every x seconds",
       "de": "Gereätepräzenz alle x Sekunden testen",
       "fr": "Presence scan every x seconds",
       "ru": "Presence scan every x seconds",
       "it": "Presence scan every x seconds",
       "es": "Presence scan every x seconds",
       "pt": "Presence scan every x seconds"
    }
};
